default:
  interruptible: true

stages:
  - lint
  - test
  - build
  - scan
  - publish

variables:
  PUBLISH_IMAGE: 'docker.io/alikov/ddam'
  PACKAGE_NAME: ddam
  DOCKER_HUB_REGISTRY: docker.io
  QUAY_IO_REGISTRY: quay.io
  PYTHON_CI_IMAGE: alikov/ci-python:python3.13
  CI_VERSION_TOOLS_IMAGE: alikov/ci-version-tools:0.2.0
  BUILDAH_CI_IMAGE: buildah/stable:v1.39.3
  TRIVY_CI_IMAGE: aquasec/trivy:0.61.0
  TRIVY_NO_PROGRESS: "true"
  # https://aquasecurity.github.io/trivy/v0.59/docs/configuration/filtering/#trivyignoreyaml
  TRIVY_IGNOREFILE: ./.trivyignore.yaml
  PYTHON_BASE_IMAGE: python:3.13.3-slim-bookworm

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "web"
    # https://docs.gitlab.com/ci/pipelines/downstream_pipelines/#dynamic-child-pipelines
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

.with-local-pip-repo:
  cache:
    - key:
        files:
          - poetry.lock
      paths:
        - ci/pip-repo

.with-registry-login:
  before_script:
    - |
      set -eu
      if [ -n "${CI_REGISTRY_USER:+notempty}" ]; then
          printf -- '%s' "$CI_REGISTRY_PASSWORD" \
              | sudo -u build --preserve-env=REGISTRY_AUTH_FILE buildah login \
                     --username "$CI_REGISTRY_USER" \
                     --password-stdin \
                     "$CI_REGISTRY"
      fi

.with-trivy-cache:
  variables:
    TRIVY_CACHE_DIR: ci/cache/trivy
  cache:
    - key: trivy
      paths:
        - $TRIVY_CACHE_DIR

version:
  image: "${DOCKER_HUB_REGISTRY}/${CI_VERSION_TOOLS_IMAGE}"
  stage: .pre
  variables:
    GIT_DEPTH: 0
  script:
    - project-version
        --version-source poetry
        --git-version-tag-prefix v
        ${CI_COMMIT_TAG:+--git-tag "$CI_COMMIT_TAG"}
        env-vars | tee version.env
  artifacts:
    reports:
      dotenv:
        - version.env

requirements:
  image: "${DOCKER_HUB_REGISTRY}/${PYTHON_CI_IMAGE}"
  extends:
    - .with-local-pip-repo
  stage: .pre
  script:
    - poetry export --format requirements.txt --with dev --output requirements-dev.txt
    - mkdir -p ci/pip-repo
    - pip3 download -r requirements-dev.txt --dest ci/pip-repo
  artifacts:
    paths:
      - requirements-dev.txt

iac-check:
  extends: .with-trivy-cache
  stage: lint
  image:
    name: "${DOCKER_HUB_REGISTRY}/${TRIVY_CI_IMAGE}"
    entrypoint: [""]
  script:
    - trivy config --exit-code 3 .
  needs: []

format-check:
  image: "${DOCKER_HUB_REGISTRY}/${PYTHON_CI_IMAGE}"
  stage: lint
  script:
    - ruff format --check
  needs: []

check:
  image: "${DOCKER_HUB_REGISTRY}/${PYTHON_CI_IMAGE}"
  stage: lint
  script:
    - ruff check
  needs: []

dependency-check:
  extends: .with-trivy-cache
  stage: lint
  image:
    name: "${DOCKER_HUB_REGISTRY}/${TRIVY_CI_IMAGE}"
    entrypoint: [""]
  script:
    - trivy fs --exit-code 3 ./requirements-dev.txt

typecheck:
  extends: .with-local-pip-repo
  image: "${DOCKER_HUB_REGISTRY}/${PYTHON_CI_IMAGE}"
  stage: lint
  script:
    - python3 -m venv ci/venv
    - source ci/venv/bin/activate
    - pip install --no-index --find-links ci/pip-repo -r requirements-dev.txt
    - pip install -e .
    - mypy --python-executable "${VIRTUAL_ENV}/bin/python3" .

test:
  extends: .with-local-pip-repo
  image: "${DOCKER_HUB_REGISTRY}/${PYTHON_CI_IMAGE}"
  stage: test
  script:
    - python3 -m venv ci/venv
    - source ci/venv/bin/activate
    - pip install --no-index --find-links ci/pip-repo -r requirements-dev.txt
    - pip install -e .
    - coverage run -m pytest -v
    - coverage report
    - coverage xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build:
  image: "${DOCKER_HUB_REGISTRY}/${PYTHON_CI_IMAGE}"
  stage: build
  script:
    - poetry build
    - PACKAGE_VERSION=$(poetry version --short)
    - printf 'PACKAGE_VERSION=%s\n' "$PACKAGE_VERSION" >package-version.env
  artifacts:
    paths:
      - dist
    reports:
      dotenv:
        - package-version.env

.build-image:
  extends: .with-registry-login
  stage: build
  image: "${QUAY_IO_REGISTRY}/${BUILDAH_CI_IMAGE}"
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: $VERSION_WITHOUT_BUILD_METADATA
  script:
    - - buildah () { sudo -u build --preserve-env=SOURCE_DATE_EPOCH,REGISTRY_AUTH_FILE buildah --storage-driver=vfs ${CONTAINERS_REGISTRIES_CONF:+--registries-conf "$CONTAINERS_REGISTRIES_CONF"} "$@"; }
    - SOURCE_DATE_EPOCH=$(date +%s)
    # This export is for buildah itsef.
    - export SOURCE_DATE_EPOCH
    - buildah build
              --isolation chroot
              --format oci
              --timestamp "$SOURCE_DATE_EPOCH"
              --build-arg PACKAGE_TARBALL="${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz"
              --build-arg BASE_IMAGE="${DOCKER_HUB_REGISTRY}/${PYTHON_BASE_IMAGE}"
              --build-arg SOURCE_DATE_EPOCH="$SOURCE_DATE_EPOCH"
              --build-arg GIT_COMMIT_SHA="$CI_COMMIT_SHA"
              --arch "$ARCH"
              -t "${IMAGE}:${TAG}-${ARCH}"
              .
    - buildah inspect "${IMAGE}:${TAG}-${ARCH}"
    - buildah push "${IMAGE}:${TAG}-${ARCH}"
  needs:
    - version
    - iac-check
    - build

build-image-amd64:
  extends: .build-image
  tags:
    - amd64-capable
  variables:
    ARCH: amd64

build-image-arm64:
  extends: .build-image
  tags:
    - arm64-capable
  variables:
    ARCH: arm64

.scan-image:
  extends: .with-trivy-cache
  stage: scan
  image:
    name: "${DOCKER_HUB_REGISTRY}/${TRIVY_CI_IMAGE}"
    entrypoint: [""]
  variables:
    TRIVY_USERNAME: $CI_REGISTRY_USER
    TRIVY_PASSWORD: $CI_REGISTRY_PASSWORD
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: $VERSION_WITHOUT_BUILD_METADATA
  script:
    - trivy image "${IMAGE}:${TAG}-${ARCH}"
    - trivy image --severity HIGH,CRITICAL --exit-code 3 --ignore-unfixed "${IMAGE}:${TAG}-${ARCH}"

scan-amd64:
  extends: .scan-image
  variables:
    ARCH: amd64
  needs:
    - version
    - build-image-amd64

scan-arm64:
  extends: .scan-image
  variables:
    ARCH: arm64
  needs:
    - version
    - build-image-arm64

publish:
  interruptible: false
  image: "${DOCKER_HUB_REGISTRY}/${PYTHON_CI_IMAGE}"
  stage: publish
  script:
    - poetry publish
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/
    - when: manual
      allow_failure: true

publish-image:
  interruptible: false
  extends: .with-registry-login
  stage: publish
  image: "${QUAY_IO_REGISTRY}/${BUILDAH_CI_IMAGE}"
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: $VERSION_WITHOUT_BUILD_METADATA
  script:
    - buildah () { sudo -u build --preserve-env=REGISTRY_AUTH_FILE buildah --storage-driver=vfs ${CONTAINERS_REGISTRIES_CONF:+--registries-conf "$CONTAINERS_REGISTRIES_CONF"} "$@"; }
    - buildah manifest create "${PUBLISH_IMAGE}:${TAG}"
    - buildah manifest add "${PUBLISH_IMAGE}:${TAG}" "${IMAGE}:${TAG}-amd64"
    - buildah manifest add "${PUBLISH_IMAGE}:${TAG}" "${IMAGE}:${TAG}-arm64"
    - buildah manifest push --all "${PUBLISH_IMAGE}:${TAG}" "docker://${PUBLISH_IMAGE}:${TAG}"
    - printf 'Pushed %s\n' "${PUBLISH_IMAGE}:${TAG}"
    - if [ -n "${VERSION_IS_LATEST_RELEASE:-}" ]; then
        buildah manifest push "${PUBLISH_IMAGE}:${TAG}" "docker://${PUBLISH_IMAGE}:latest";
        printf "Pushed %s\n" "${PUBLISH_IMAGE}:latest";
      fi
  needs:
    - version
    - scan-amd64
    - scan-arm64
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/
    - when: manual
      allow_failure: true
