include:
  - .gitlab-ci.yml

reformat:
  stage: .pre
  image: "${DOCKER_HUB_REGISTRY}/${PYTHON_CI_IMAGE}"
  script:
    - ruff check --select I --fix
    - ruff format
  artifacts:
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'
    expire_in: 1 day
